cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login as login, logout as logout, logout_then_login as logout_login
from django.contrib.sitemaps.views import sitemap
from shop.sitemaps import ProductSitemap

sitemaps = {
    'products': ProductSitemap,
}


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    #url(r'^payment/', include('payment.urls', namespace='payment')),
    # url(r'^login/$', login, name='login'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^logout-then-login/$', logout_login, name='logout_then_login'),
    url(r'^', include('shop.urls', namespace='shop'), ),
    # sign_in/sign_out via FB
    url(r'^api/social/', include('rest_framework_social_oauth2.urls')),
    url('social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login as login, logout as logout, logout_then_login as logout_login
from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    # url(r'^login/$', login, name='login'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='наименование')
    slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name='краткое наименование')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True, verbose_name='наименование')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='изображение')
    description = models.TextField(max_length=2000,blank=True, verbose_name='описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='цена')
    stock = models.PositiveIntegerField(verbose_name='в наличии')
    available = models.BooleanField(default=True, verbose_name='наличие')
    created = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='дата обновления')

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
    avatar = models.CharField(max_length=350, default='Тут будет Ваше фото')
    phone = models.CharField(max_length=400, blank=True, verbose_name='телефон')
    address= models.CharField(max_length=500, blank=True, verbose_name='адрес')

    def __str__(self):
        return self.user.get_full_name()

shop/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Ой! С паролем как-то неудобно получилось...')
        return cd['password2']

shop/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Category, Product
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, UserRegistrationForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Авторизация успешна')
                    # return HttpResponseRedirect('../cart/templates/cart/detail.html')
                else:
                    return HttpResponse('Пользователь отсутствует')
            else:
                return HttpResponse('Неверный login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    HttpResponseRedirect('shop/base.html')

# @login_required
# def dashboard(request):
#     return render(request, 'registration/dashboard.html', {'section': 'dashboard'})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)

        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            # Create the user profile
            return render(request,
                          'shop/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'shop/register.html', {'user_form': user_form})


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products_list = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products_list = products_list.filter(category=category)

        page = request.GET.get('page')
        paginator = Paginator(products_list, 2)

        try:
            products_list = paginator.page(page)

        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            products_list = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            products_list = paginator.page(paginator.num_pages)


    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products_list})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


# def user_login(request):
#     username = request.POST['username']
#     password = request.POST['password']
#     user = auth.authenticate(username=username, password=password)
#     if user is not None and user.is_active:
#         # Правильный пароль и пользователь "активен"
#         auth.login(request, user)
#         # Перенаправление на "правильную" страницу
#         return HttpResponseRedirect("/account/loggedin/")
#     else:
#         # Отображение страницы с ошибкой
#         return HttpResponseRedirect("/account/invalid/")

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
{#    <script src="https://ucarecdn.com/libs/widget/3.2.1/uploadcare.full.min.js"></script>#}
    <title>{% block title %}Магазин{% endblock %}</title>
{#    {% load bootstrap3 %}#}
{#    <script src="{% bootstrap_jquery_url %}"></script>#}
{#    {% bootstrap_javascript %}#}

    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <a href="/" class="logo">Джанго-ШОП</a>

    <div id="register">
        {% if request.user.is_anonymous %}
            <a href="{% url "shop:register" %}">Зарегистрироваться</a>
        {% endif %}
    </div>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li>Добрый день, {{ request.user.username }}</li>
                <li><a href="{% url "shop:logout" %}">Выйти</a></li>
            </ul>
            {% endif %}
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Ваша корзина:
                    <a href="{% url "cart:cart_detail" %}">
                        {{ total_items }} штук{{ total_items|pluralize }},{{ cart.get_total_price }}грн
                    </a>
                {% else %}
                    Ваша корзина пуста.
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>


{#Для загрузки файлов#}
{#    <script>#}
{#        UPLOADCARE_LOCALE = "ua";#}
{#        UPLOADCARE_LIVE = false;#}
{#        UPLOADCARE_PUBLIC_KEY = "92862fdbd5114f940ea1";#}
{#    </script>#}

<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="{% static 'js/jquery.backgroundvideo.min.js' %}"></script>
    <script>
      $(document).ready(function() {
        var videobackground = new $.backgroundVideo($('body'), {
          "align": "centerXY",
          "width": 1280,
          "height": 720,
          "path": "/static/media/",
          "filename": "q2",
          "types": ["mp4","ogg","webm"],
          "preload": true,
          "autoplay": true,
          "loop": true
        });
      });
    </script>
</body>
</html>

shop/templates/shop/register.html
{% extends "shop/base.html" %}

{% block title %}Создать учетную запись{% endblock %}

{% block content %}
    <h1>Создать учетную запись</h1>
    <p>Пожалуйста, заполните форму:</p>
    <form action="." method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Создать учетную запись"></p>
    </form>
{% endblock %}

shop/templates/shop/register_done.html
{% extends "shop/base.html" %}

{% block title %}Добро пожаловать!{% endblock %}

{% block content %}
    <h1>Добро пожаловать в Джанго-магазин! {{ new_user.first_name }}!</h1>
    <p>Ваша учетная запись создана. Теперь вы можете сделать <a href="{% url "login" %}">log in</a>.</p>
{% endblock %}